### ISSUE TITLE
RHEL Dockerfile is unmaintained

### ISSUE THREAD

**Issue by hjudt** [container-lisp/s2i-lisp#1]
Since I have no access to RHEL with license, I can't test it and have not maintained it to be on a par with the CentOS image. If someone contributes to the Dockerfile that would be great, otherwise it might be wise to ditch it or at least inform users about its current desolate state.

**Comment by atgreen** [comment]
I plan on fixing this.

BTW, you can get a RHEL subscription for free at developers.redhat.com.

**Comment by atgreen** [comment]
It's working now.  Just 'make OS=rhel7' on a RHEL7 box.
