### ISSUE TITLE
Patch quicklisp in install.lisp

### ISSUE THREAD

**Issue by atgreen** [container-lisp/s2i-lisp#4]
We patch the quicklisp client to automatically take advantage of a local quicklisp mirror.  This should be done in install.lisp rather than after because now it has to be recompiled the first time it is used. Also, packages installed during install.lisp never come from the mirror.

**Comment by hjudt** [comment]
Does this work for you? I can't test it now, but it seems to execute "patch" properly and I have not seen any error messages.

**Comment by atgreen** [comment]
Thanks - this looks great
