### ISSUE TITLE
Provide prometheus metrics

### ISSUE THREAD

**Issue by atgreen** [container-lisp/s2i-lisp#7]
We should integrate this so users can optionally ship metrics to prometheus...
https://github.com/deadtrickster/prometheus.cl

**Comment by hjudt** [comment]
It seems this can simply be quickloaded? If so, the user can do it in the build/run script.

**Comment by atgreen** [comment]
It's a little more complicated than that, but I agree it doesn't belong here.  I'll put it in the sample web app.
I just made it work for red-light-green-light, and it's very nice.
