### ISSUE TITLE
Problem using sly

### ISSUE THREAD

**Issue by atgreen** [container-lisp/s2i-lisp#8]
When I set DEV_BACKEND to slynk, I get errors shown in the attached log file.

[quicklisp-mirror-2-6rccp.log](https://github.com/container-lisp/s2i-lisp/files/2799971/quicklisp-mirror-2-6rccp.log)

**Comment by hjudt** [comment]
From the logs this looks like a simple typing mistake, so I am closing this. You can see how to configure it for sly in my sample app: https://github.com/hjudt/sample-lisp-app/blob/master/.s2i/environment.
